driver:
    config:
        sshConnection:
            privateKey: ENC[AES256_GCM,data:jlBkMJNpaKPtmgS3gIPDem3MYkI/G/jAyIJpWJM5KbvIzMDy3/KfBJvpNikzV7l0euZ7aJYiPZHxSlLrTAa0FoaImtS9yIXWVxhTo+nV5/47OmlmG/E6R1g7ycXHu9Yp8T8U4UsWvfSTRVP5JH8WQRbi3auTH2Lal9nVXBu+C3s5AFu8uuZOD5WpHl21u6R6GBL/0LrcTqp/tHkxU+Gu6Juh6lQx+TMtDNihE/yKCJM2n2oQ9PnHWDPnfDmY9j5gP9Wfx+DwGCMfEP4puMm+YtOMG0l3I0NdXAHANq29b0dXyB13CJCVi3pk1zIzqcLWipLQAzabqVQVwvQNB9xyzUVBlHbeX2jYtL89WZ7gvDLG4npO0zzv17uDwpY+MrtADcZPhiOxTJlNpjafZknY+9/cEQf7PmloWkgy1wKbNSAMMwCzcWpLsuNkGkdvd9Iv8rKfAuYkE6xplN5J5q7UWK97Y3ejqRGTJreaRKaiZMpgmsAkcmyh1KC70x4JEqmHxzfI,iv:8YNpFZ24DwZ+yUfoYP5KO5idD0c5/r/wMA6/6/M8H1I=,tag:wh1csTsM7GPeKppJv2TuOA==,type:str]
        httpConnection:
            apiKey: ENC[AES256_GCM,data:dqkuKObyXZLYHT/mTwYjaeuhwjX2mAUXOa08zK3nRqoTyMpBs3vOpZLjgAou1yhJtqJ2zT+UQ6Wo2rdsvJAKPlvJ,iv:kB+H4A01YKiK9ep63PoUKA2XxG2mfo2A5oGFNwCmTOM=,tag:ixfL7rX+NpUzzkS9sGnoSQ==,type:str]
sops:
    age:
        - recipient: age1ctm3nz3aqghfde3hwgy8w80qlhjh972d4sz0hhq28qnf4esnu35q5suu83
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVczREcTNQTGdMbWJhMVlU
            ZnZPUjh3QVVQRzF4ZmV4eXl4WlFNWmg0UGxRCmRDTTY0VlpGbmpTVUZlOHVOUWdJ
            b0w2NkZ6TXI1U1ZRUWZQRDAwMWlEY0UKLS0tIFhyTVg2NjNSUWhNMld1UFh2eklR
            ODRCTGVNZ1daci9TWElzTjByRWU4TjAKGqMm/KeRCi+Ug1KYK/XDg80cXRfeGgRF
            izMGfk+GyDwKeZyt8rnnKWqbExj4c0cg8+f7/oWOjvC/R1GnKlMwtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T08:58:39Z"
    mac: ENC[AES256_GCM,data:ri+fpAYiNSx1NEdFDRItJZbMUy8vI/C49jp5pWDoGLdxHQLpLaO0umFWnVOJmhhjo9vAJmSJyk3FWV89kUJsopCPXI3CW3aQvz1SXi3Gf9nGER6htPNpaluCeJ/HODjt0oT7hwHPaycuqQUplZjosfzE9XW9O4thTslPQd0NWeg=,iv:RiKIl6PbzpCCcQdvh/e9+8m+6iGdyLyvdQXvyC5o5NY=,tag:IqA924wbKbUF7YO5V/SFsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
