driver:
  config:
    sshConnection:
      host: truenas.lan
      username: km
    httpConnection:
      host: truenas.lan
    zfs:
      datasetParentName: NVME/k8s-vols/data
      detachedSnapshotsDatasetParentName: NVME/k8s-vols/snaps
    iscsi:
      targetPortal: "truenas.lan:3260"
      targetGroups:
        - targetGroupPortalGroup: 2
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
