stages:
  - infrastructure
  - configuration

# 1. Поднятие ВМ (Аналог make infra)
deploy_infrastructure:
  stage: infrastructure
  tags:
    - shell
  before_script:
    - echo ">>> Настройка гибридных зеркал Terraform (Yandex + direct)..."
    - |
      cat <<EOF > ~/.terraformrc
      provider_installation {
        network_mirror {
          url = "https://terraform-mirror.yandex.ru/"
          include = ["registry.terraform.io/*/*"]
        }
        direct {
          exclude = ["registry.terraform.io/*/*"]
        }
      }
      EOF
  script:
    - echo ">>> Развертывание инфраструктуры KVM..."
    - cd terraform/infra-vms && terraform init && terraform apply -auto-approve
    - cd ../cluster-nodes && terraform init && terraform apply -auto-approve

# 2. Установка Kubernetes (Аналог make k8s-base)
configure_kubernetes:
  stage: configuration
  tags:
    - shell
  before_script:
    # Подгружаем SSH-ключ из секретов GitLab для Ansible
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - export ANSIBLE_HOST_KEY_CHECKING=False
  script:
    - echo ">>> Установка Kubernetes и сетевой фабрики..."
    - sleep 30
    - ansible-playbook -i ansible/inventory/generated_hosts.ini ansible/playbooks/01_prepare.yml
    - ansible-playbook -i ansible/inventory/generated_hosts.ini ansible/playbooks/02_install_k8s.yml
    - ansible-playbook -i ansible/inventory/generated_hosts.ini ansible/playbooks/02_init_master.yml
    - ansible-playbook -i ansible/inventory/generated_hosts.ini ansible/playbooks/02_join_workers.yml
    - ansible-playbook -i ansible/inventory/generated_hosts.ini ansible/playbooks/01_containerd_mirrors.yml
    # Настройка сети и балансировщика
    - export KUBECONFIG=$HOME/.kube/config
    - kubectl wait --for=condition=Ready nodes --all --timeout=120s
    - kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
    - kubectl wait --namespace metallb-system --for=condition=ready pod -l component=controller --timeout=300s
    - kubectl wait --namespace metallb-system --for=condition=ready pod -l component=speaker --timeout=300s
    - sleep 15
    - kubectl apply -f kubernetes/core/metallb-config.yaml
