stages:
  - lint
  - deploy_infra
  - deploy_apps

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

before_script:
  # 1. Устанавливаем нужные пакеты (добавлен openssl для Helm)
  - apk add --no-cache make ansible openssh-client curl git openssl

  # 2. Умная маршрутизация зеркал: базовые пакеты с Яндекса, экзотика с комьюнити
  - |
    cat <<EOF > ~/.terraformrc
    provider_installation {
      network_mirror {
        url = "https://terraform-mirror.yandexcloud.net/"
        include = ["registry.terraform.io/hashicorp/*"]
      }
      network_mirror {
        url = "https://terraform-registry-mirror.ru/"
        include = ["registry.terraform.io/dmacvicar/*"]
      }
      direct {
        exclude = ["*/*"]
      }
    }
    EOF

  # 3. Скачиваем kubectl
  - curl -LO "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
  - chmod +x kubectl && mv kubectl /usr/local/bin/

  # 4. Скачиваем Helm
  - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sh

  # 5. Настройка SSH: копируем, удаляем виндовые символы и добавляем пустую строку
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - tr -d '\r' < "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
  - echo "" >> ~/.ssh/id_ed25519
  - chmod 600 ~/.ssh/id_ed25519
  - ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_ed25519
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config  

  # 6. Настройка путей для Makefile (Инвентарь и Кубер)
  - mkdir -p ansible/inventory && cp "$ANSIBLE_HOSTS" ansible/inventory/generated_hosts.ini
  - mkdir -p ~/.kube && cp "$KUBECONFIG" ~/.kube/config

  # 7. Подготовка пароля Vault и отключение проверки хостов SSH
  - echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
  - export ANSIBLE_VAULT_PASSWORD_FILE=$(pwd)/.vault_pass
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

# --- СТАДИИ ПАЙПЛАЙНА ---

linting:
  stage: lint
  script:
    - terraform -chdir=terraform init -backend=false
    - terraform -chdir=terraform validate
    - ansible-playbook --syntax-check -i ansible/inventory/generated_hosts.ini ansible/site.yml

infrastructure:
  stage: deploy_infra
  script:
    - make all
  only:
    - main
  when: manual # <- Твой предохранитель от случайного деплоя

applications:
  stage: deploy_apps
  script:
    - make apps
  only:
    - main
