---
- name: Open Monitoring Ports
  hosts: compute
  become: yes
  tasks:
    - name: Allow GPU Exporter port in UFW
      community.general.ufw:
        rule: allow
        port: '9835'
        proto: tcp
      ignore_errors: yes

    - name: Allow GPU Exporter port in Firewalld
      ansible.posix.firewalld:
        port: 9835/tcp
        permanent: yes
        state: enabled
        immediate: yes
      ignore_errors: yes
