---
- name: Генерация секретных конфигов из Vault
  hosts: localhost
  connection: local
  vars_files:
    - vault.yml
  tasks:
    - name: Создание zfs-iscsi-secrets.yaml из шаблона
      template:
        src: ../templates/zfs-iscsi-secrets.j2
        dest: "../../kubernetes/core/truenas-csi/zfs-iscsi-secrets.yaml"
        mode: '0600' # Права только для владельца!

    - name: Генерация конфига Alertmanager с секретами
      template:
        src: ../templates/alertmanager-values.j2
        dest: "../../kubernetes/core/alertmanager-values-secrets.yaml"
        mode: '0600'
