alertmanager:
    config:
        global:
            resolve_timeout: ENC[AES256_GCM,data:+eI=,iv:pgOonH8rwJeKWrcuMfkGlccFvYtYVVIUeJC6pwKEkzY=,tag:BpCL+99SAHXXve++IS0F5w==,type:str]
        route:
            group_by:
                - ENC[AES256_GCM,data:QZU+iyx2YlJo,iv:GWd9Ls3GRFDEKU4OGcLQHAkMpEwfkcupluRr533EI5k=,tag:clpF3jvkRe7PNe7+lXvb8Q==,type:str]
                - ENC[AES256_GCM,data:HTzm,iv:Tu99qcrYZQWFxdw9sYsRKVa/v63qnbAtQFqlyXKJQwA=,tag:GID45Q9Fyus6njtviM2BIA==,type:str]
                - ENC[AES256_GCM,data:PGGHU1AxCoo=,iv:Va5UxKWQmG50pFf2iNdo7hVtnsr/aT1JNsTO6fFinkU=,tag:XS/djX7lbN6OwFJ+RtSVOw==,type:str]
            group_wait: ENC[AES256_GCM,data:y2aB,iv:nPuYqYdnDMPQQPx1fEWAT+QlZZPUYkkdrJ9hRwNZXt0=,tag:QzxJifCpqozLDfQcwvIvog==,type:str]
            group_interval: ENC[AES256_GCM,data:Nxg=,iv:YSlMiWg7MvZ1NLE6e1BR9MrUQSTqRLMV1upiszBVAms=,tag:bQYTkhLnObAOVAfwFa1pYA==,type:str]
            repeat_interval: ENC[AES256_GCM,data:pZk=,iv:o1685dw8KhGmSmdLGDOytiPL5dQHD2MMHABAsI2IBBU=,tag:xIMj8pfA76hT4Wd+jLYcOA==,type:str]
            receiver: ENC[AES256_GCM,data:O5bb1n2ZV4sQLUIlO1nH+YQ=,iv:ze4ZZY42LLth1hvBrrz+b4z34ZZ4b3S4mCsql2CXiI4=,tag:Jkml0AECgTmjdxy4R2LsjA==,type:str]
            routes:
                - matchers:
                    - ENC[AES256_GCM,data:OztrGX27kZHG26G3804u6TFysq6bOccUPAPpaUgMGPBVHmE=,iv:thy29pkJ2GcR9Hd3WhQLmMt1PBpsyeeahMnXk/4G8sY=,tag:ENQa95SsRsOQJngtYtwIfw==,type:str]
                  receiver: ENC[AES256_GCM,data:6P+r0UXNsapv,iv:yVVPvHjTSQEBttNy6JynHQsvaUjD8/w7zcOXT2143GU=,tag:thM9+i44ejMfwRoJxAjzvg==,type:str]
                - matchers:
                    - ENC[AES256_GCM,data:fJLMj66LhqNDHnoT92VFj8c0ow==,iv:lRdgSKUQuCd6HLKwOworzZggOuNyFeGAp9oteVdN550=,tag:8lWYgDSpSjJznM2/GySaHw==,type:str]
                  receiver: ENC[AES256_GCM,data:in/wo2D/gKz6/4yohAMn14I=,iv:Y8tsjQtlzkMNaO/MOsi9hNb4QtjMKkjA0Mr6yHqGDjY=,tag:IgtVn7EZQ3hKvT75Uhtrcw==,type:str]
                - matchers:
                    - ENC[AES256_GCM,data:24n/sp47w9pGm8mtAJuRXEV1,iv:72dzfZMrjyCYh/5mMNqvBe+Ja6tlj3gT/nN4qS8BEYM=,tag:R2qK3COCYBb/1nG20HVMgA==,type:str]
                  receiver: ENC[AES256_GCM,data:fnoQH9lkR9iu310GZn/1dPk=,iv:X436urYspQZ9rOzKtBw/ug3Dicy+kKcM8RcuUtdAjWQ=,tag:YIAwpaYLzHA5sqo2YbrGJA==,type:str]
        receivers:
            - name: ENC[AES256_GCM,data:cPOdiNDw8eoe,iv:yGBztgcXrJnD5+htum4UhPmTh3h1BwYG4yt3/UTLcU8=,tag:X430muW6nrK3t460Uta/gA==,type:str]
            - name: ENC[AES256_GCM,data:G97uF9L3fVj4yPtS9h9e16Q=,iv:MXJmGN9ajf+EcL4h3bx68KYxXVX4E6jdKPDbRTq/3eg=,tag:f7i7LzRftXbEdezMWiBqxw==,type:str]
              telegram_configs:
                - bot_token: ENC[AES256_GCM,data:MKqrSgaBX+hJ5t3SJ0LmV3nvAJMiSW0EqulB0eTbFFHQRbZnH9XyOA99x3YU/g==,iv:SbfPedoRev5+C5/GZXMNXA7BEXG7mPOqR0LNH5TiukE=,tag:Ll9jkngi/tD2sAR70h+fAg==,type:str]
                  chat_id: ENC[AES256_GCM,data:Ulyd6hIBX2D2ug==,iv:P7sI3TQrVmWJtJk3DCaMT8zN6Wu6iAmobV4vrkgWjMI=,tag:zabWi2jXm55HNcMITy+xjA==,type:int]
                  parse_mode: ENC[AES256_GCM,data:5sjiHw==,iv:BdedupYWR18Uv6VfGYCJLWciO+reUMHR+XHB43ndI+A=,tag:i23aQ45zMhYyL8vwlCCHwQ==,type:str]
                  send_resolved: ENC[AES256_GCM,data:I7YCnQ==,iv:MFGkprTP1xGu1/U43O1wxalMTz3G31TARu/UemE0Oh8=,tag:gXGRxxXOOhHT5ADg1K/2bw==,type:bool]
                  message: ENC[AES256_GCM,data:QCAVRmtW0EfvIcd97Q3Cg2T8xUIbD4LozkPcDmopXaZKEtApN7Oft6oaXKSpwS77RxO8KlJIeVl7pYo6cae4N46odvQVkVVWZapoU1igZo9i7gX6wdZfK0/lDCx2bRrYYv8CDNwnF/MW5MLsDVE++GDO/4aHHbLEy/vKsMxQtC/v2bGGBg7zIfsNFf0JGe7Bp4pO0YsnmdtxUSDxhaSYTfq0WPmpfUwDGQV9f+qbcuHx+i+Wqeb/HDhLLcT7UGEoETEFEEBpcZesdOHfVT8GbKknqsJ2GU7Jm96VDn+U5nfy8rd07Ga0vwGgRDe5cikMfZXZL5hXiKsfnqYVdyGJh0R3iOni/YBBqtp9j5Arm14ypfTwM9NfNw9P5EnafZ380YAdDpsEoF+hU+kzw6L9pCn3/ARdNMoaI6Mpq2RLOJFbBZzrVkG11vvgfXeTpWlqE+YTwRkCG1GdZhxyCdHIJ8fU9UDbeSVDPtNZmBcf6kuaIH5Hit3wtprYU5E1TCbdx46+k9fORc05Cx2f+PHL+GcEB2PlJLFFv6OHvlC5do+g9vuV87Ucg7SRMVRElteoPYFSuj7o2vCEQTd4BFaV+r3UkwVssfJQuDI08AMwW3It/sf2MbUV6l7yNE+kdmGX6QU4e7dhvZKA9Int24wI9QwIV8BmDZ0DE/D1XEH3jdJDfT/QFY9/nQFgMEajCfI7ZNgSNUYZvdpZaFVPDPY=,iv:E+ykeG5TF7hheZ2oCbbY8iExOyeyovLEm4IoSub65pY=,tag:l2VjpTOyGB1g7vRRkGKKzw==,type:str]
sops:
    age:
        - recipient: age1ctm3nz3aqghfde3hwgy8w80qlhjh972d4sz0hhq28qnf4esnu35q5suu83
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaU4xRkxMY2lNeXhqQkhO
            ZXo3WGYwRVlwZk5ndjIvRlgvZGM1QUVCcFhZCnJHcWFqTlBwbTl2cEdRazhBYkdF
            a1llb1FwTXNVbGtsOWFPVkNveXFzeVEKLS0tIGllTFF4V2xOWjYxbDhZU0ZJallL
            SHBJbGtZY1lpMTlSZ2xjLzFFVmVMSGsKz9VaqH0/ETKKLFjAiv1qqQkU7bjpfCdM
            U2e6vUaSVCHWiG8Q6voKhErckpL0O7XGHN+hH0a236AvHut3yjrZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T08:58:39Z"
    mac: ENC[AES256_GCM,data:gc33nEHAkWzFfQEMRUpcefkXju/rXffQF5ccKBbSHTQ4S1zsC984H23ey44FstHkmEOeb8yFkow+mMd1jQBpa1CC/Ru6LbgiWESn5KSLEawtIvCI9B1G6CKhQYOJt8C3r9MBxkPqMSNOvfkgC0gqGpBdNALy4JkBoqRsZY4T2mg=,iv:gqXkQpZQ48rdaO1H4JikLB0fXbXedpIwO6k1yCnnIoc=,tag:i/NaleN7K/ru4m6+TH7L3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
